// TokenRhythm (基元律动) + NVIDIA (英伟达) provider presets for opencode
// Installed by the TokenRhythm preset installer.
// Registers models (multimodal models flagged) so opencode knows they
// support image/video attachments even if the config is regenerated.

const TokenRhythmPresetModels = {
      {"id": "kimi-k2.5", "providerID": "tokenrhythm", "name": "Kimi K2.5", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 4.0, "output": 21.0, "cache": {"read": 0.8, "write": 0}}, "limit": {"context": 256000, "output": 64000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "kimi-k2.6", "providerID": "tokenrhythm", "name": "Kimi K2.6", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 6.5, "output": 27.0, "cache": {"read": 1.3, "write": 0}}, "limit": {"context": 256000, "output": 128000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "kimi-k2.7-code", "providerID": "tokenrhythm", "name": "Kimi K2.7 Code", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 6.5, "output": 27.0, "cache": {"read": 1.3, "write": 0}}, "limit": {"context": 256000, "output": 16000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "seed-2.1-pro", "providerID": "tokenrhythm", "name": "Seed 2.1 Pro", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": true, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 6.0, "output": 30.0, "cache": {"read": 1.2, "write": 0}}, "limit": {"context": 262144, "output": 131072}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "seed-2.1-turbo", "providerID": "tokenrhythm", "name": "Seed 2.1 Turbo", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": true, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 3.0, "output": 15.0, "cache": {"read": 0.6, "write": 0}}, "limit": {"context": 262144, "output": 131072}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "qwen3.8-max", "providerID": "tokenrhythm", "name": "Qwen 3.8 Max", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 12.0, "output": 36.0, "cache": {"read": 1.5, "write": 0}}, "limit": {"context": 1000000, "output": 131072}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "deepseek-v4-flash", "providerID": "tokenrhythm", "name": "DeepSeek V4 Flash", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 1.0, "output": 2.0, "cache": {"read": 0.2, "write": 0}}, "limit": {"context": 1000000, "output": 384000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "deepseek-v4-pro", "providerID": "tokenrhythm", "name": "DeepSeek V4 Pro", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 12.0, "output": 24.0, "cache": {"read": 1.0, "write": 0}}, "limit": {"context": 1000000, "output": 384000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "deepseek-v4-flash-0731", "providerID": "tokenrhythm", "name": "DeepSeek V4 Flash 0731", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 3.0, "output": 9.0, "cache": {"read": 0.1, "write": 0}}, "limit": {"context": 1000000, "output": 384000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "deepseek-v4-pro-0813", "providerID": "tokenrhythm", "name": "DeepSeek V4 Pro 0813", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 9.0, "output": 27.0, "cache": {"read": 0.3, "write": 0}}, "limit": {"context": 1000000, "output": 384000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "glm-5", "providerID": "tokenrhythm", "name": "GLM-5", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 6.0, "output": 22.0, "cache": {"read": 1.5, "write": 0}}, "limit": {"context": 1000000, "output": 128000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "glm-5.1", "providerID": "tokenrhythm", "name": "GLM-5.1", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 8.0, "output": 28.0, "cache": {"read": 2.0, "write": 0}}, "limit": {"context": 200000, "output": 128000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "glm-5.2", "providerID": "tokenrhythm", "name": "GLM-5.2", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 8.0, "output": 28.0, "cache": {"read": 2.0, "write": 0}}, "limit": {"context": 1000000, "output": 128000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "mimo-v2.5-pro", "providerID": "tokenrhythm", "name": "MiMo 2.5 Pro", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 3.0, "output": 6.0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 256000, "output": 256000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "minimax-m2.5", "providerID": "tokenrhythm", "name": "MiniMax M2.5", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 2.1, "output": 8.4, "cache": {"read": 0, "write": 0}}, "limit": {"context": 200000, "output": 200000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "minimax-m2.7", "providerID": "tokenrhythm", "name": "MiniMax M2.7", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 2.1, "output": 8.4, "cache": {"read": 0, "write": 0}}, "limit": {"context": 200000, "output": 192000}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "qwen3.7-max", "providerID": "tokenrhythm", "name": "Qwen 3.7 Max", "api": {"id": "openai", "url": "https://tokenrhythm.studio/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 12.0, "output": 36.0, "cache": {"read": 2.4, "write": 0}}, "limit": {"context": 1000000, "output": 131072}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"}
    }

export const TokenRhythmPreset = async () => ({
  provider: {
    id: "tokenrhythm",
    models: async () => TokenRhythmPresetModels,
  },
})

const NvidiaPresetModels = {
      {"id": "minimaxai/minimax-m3", "providerID": "nvidia", "name": "MiniMax M3 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": true, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 1000000, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "moonshotai/kimi-k3", "providerID": "nvidia", "name": "Kimi K3 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": true, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 1048576, "output": 32768}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "moonshotai/kimi-k2.6", "providerID": "nvidia", "name": "Kimi K2.6 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": true, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 256000, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "meta/llama-3.2-11b-vision-instruct", "providerID": "nvidia", "name": "Llama 3.2 11B Vision (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 128000, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "meta/llama-3.2-90b-vision-instruct", "providerID": "nvidia", "name": "Llama 3.2 90B Vision (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 128000, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", "providerID": "nvidia", "name": "Nemotron Nano VL 8B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 128000, "output": 4096}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/nemotron-nano-12b-v2-vl", "providerID": "nvidia", "name": "Nemotron Nano 12B VL v2 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": true, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 128000, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", "providerID": "nvidia", "name": "Nemotron 3 Nano Omni 30B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": true, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "microsoft/phi-3-vision-128k-instruct", "providerID": "nvidia", "name": "Phi-3 Vision 128K (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 128000, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "google/gemma-3-4b-it", "providerID": "nvidia", "name": "Gemma 3 4B IT (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "google/gemma-3-12b-it", "providerID": "nvidia", "name": "Gemma 3 12B IT (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "google/gemma-4-31b-it", "providerID": "nvidia", "name": "Gemma 4 31B IT (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 262144, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "stepfun-ai/step-3.7-flash", "providerID": "nvidia", "name": "StepFun Step 3.7 Flash (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 262144, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "thinkingmachines/inkling", "providerID": "nvidia", "name": "Inkling (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "meta/muse-glimmer-30b", "providerID": "nvidia", "name": "Muse Glimmer 30B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/vila", "providerID": "nvidia", "name": "VILA (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": true, "toolcall": true, "input": {"text": true, "audio": false, "image": true, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 32768, "output": 4096}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "deepseek-ai/deepseek-v4-flash-0731", "providerID": "nvidia", "name": "DeepSeek V4 Flash 0731 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 1000000, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "z-ai/glm-5.2", "providerID": "nvidia", "name": "GLM-5.2 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 1000000, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "meta/llama-3.1-8b-instruct", "providerID": "nvidia", "name": "Llama 3.1 8B Instruct (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "meta/llama-3.3-70b-instruct", "providerID": "nvidia", "name": "Llama 3.3 70B Instruct (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/llama-3.1-nemotron-70b-instruct", "providerID": "nvidia", "name": "Nemotron 70B Instruct (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/llama-3.1-nemotron-ultra-253b-v1", "providerID": "nvidia", "name": "Nemotron Ultra 253B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/llama-3.3-nemotron-super-49b-v1", "providerID": "nvidia", "name": "Nemotron Super 49B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/llama-3.3-nemotron-super-49b-v1.5", "providerID": "nvidia", "name": "Nemotron Super 49B v1.5 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/nemotron-3-super-120b-a12b", "providerID": "nvidia", "name": "Nemotron 3 Super 120B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/nemotron-3-ultra-550b-a55b", "providerID": "nvidia", "name": "Nemotron 3 Ultra 550B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/nemotron-3.5-lightning-30b-a3b", "providerID": "nvidia", "name": "Nemotron 3.5 Lightning 30B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/nemotron-nano-3-30b-a3b", "providerID": "nvidia", "name": "Nemotron Nano 3 30B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "nvidia/nemotron-mini-4b-instruct", "providerID": "nvidia", "name": "Nemotron Mini 4B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "mistralai/mistral-large", "providerID": "nvidia", "name": "Mistral Large (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "mistralai/mistral-large-2-instruct", "providerID": "nvidia", "name": "Mistral Large 2 (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "mistralai/mistral-nemotron", "providerID": "nvidia", "name": "Mistral Nemotron (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "mistralai/mixtral-8x22b-v0.1", "providerID": "nvidia", "name": "Mixtral 8x22B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 65536, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "openai/gpt-oss-20b", "providerID": "nvidia", "name": "GPT-OSS 20B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "openai/gpt-oss-120b", "providerID": "nvidia", "name": "GPT-OSS 120B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": true, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 16384}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "google/codegemma-7b", "providerID": "nvidia", "name": "CodeGemma 7B (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 16384, "output": 4096}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"},
      {"id": "zyphra/zamba2-7b-instruct", "providerID": "nvidia", "name": "Zamba2 7B Instruct (英伟达)", "api": {"id": "openai", "url": "https://integrate.api.nvidia.com/v1", "npm": "@ai-sdk/openai-compatible"}, "capabilities": {"temperature": true, "reasoning": false, "attachment": false, "toolcall": true, "input": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "output": {"text": true, "audio": false, "image": false, "video": false, "pdf": false}, "interleaved": false}, "cost": {"input": 0, "output": 0, "cache": {"read": 0, "write": 0}}, "limit": {"context": 131072, "output": 8192}, "status": "active", "options": {}, "headers": {}, "release_date": "2026-08-20"}
    }

export const NvidiaPreset = async () => ({
  provider: {
    id: "nvidia",
    models: async () => NvidiaPresetModels,
  },
})
